### ISSUE TITLE
Update script does not seem to work

### ISSUE THREAD

**Issue by anderse77** [flynnsbit/Top300_updates#100]
Script does not work anymore: Remote file name has no length is the rror.

Is this abandoned and no longer maintained?

**Comment by flynnsbit** [comment]
Works fine, I just ran it. You probably just messed up transferring the file, like trying to use wsftp in binary mode.  Follow the instructions and you will be fine.

**Comment by anderse77** [comment]
Which instructions? I followed the instructions in readme.md on
https://github.com/flynnsbit/Top300_updates. What do you mean trying to use
wsftp in binary mode?

**Comment by flynnsbit** [comment]
If you followed the readme you should be good.  My point was it is working.  I had a few others test as well.  It could be a few different things on your side.  

The update script should take no longer than a min or so to run.  If you aren't seeing files fly by it could be a power issue with your USB drive, it could be your internet connection, etc.
