### ISSUE TITLE
Lotus III: The Ultimate Challenge - Speed issues (game is not part of top 300 but should be)

### ISSUE THREAD

**Issue by vidarw** [flynnsbit/Top300_updates#34]
Game behaves weirdly on MiSTER with noticeable slowdown compared to emulation and/or real computers.
Slowdown seems related to various settings including choice of sound/music output, where Sound Blaster is the obvious choice for the best experience.

**Comment by FreddoUK** [comment]
thanks I'll remember this when we expand the pack.
