### ISSUE TITLE
Several games overwrite sound configuration and run in SB mode

### ISSUE THREAD

**Issue by mbaran5** [flynnsbit/Top300_updates#39]
I will edit this list as a I run through more, but the following games start in SB mode no matter what you set in the config. Many of them will skip the choices menu and jump right to SB as well. 

- Dune
- Wing Commander(s)
- Where in the World is Carmen San Diego
- SimCity 2000 
- Star Wars X Wing/TIE
- Prince of Persia

**Comment by FreddoUK** [comment]
can you check a few things for me please?

- are you on the latest version of the pack (updated via updater) ?
- is jchoice.exe in e:\utils ?

**Comment by mbaran5** [comment]
Yes latest version

No, jchoice.exe is not in utils. This would explain why some games seem to fly right past the choices screen, but odd that others still allow for the choice...

![image](https://user-images.githubusercontent.com/583865/104230432-6ec4ef80-5402-11eb-92e3-9c22da5a2f7f.png)

**Comment by FreddoUK** [comment]
hm, currently the updater script doesn't update itself, you didn't use an older version of the script did you? if so retrying with the latest might fix this.

**Comment by mbaran5** [comment]
I nabbed the script only about 5 days ago, but ran it again and it seems to have worked. I am not sure if the script terminated prematurely last time but I now see the updated files inside the VHD. Let me retry a few of the games above and see. Thanks, no idea what happened there.

**Comment by mbaran5** [comment]
Games tested all seem fine now when selecting MT-32 from choice menu.
