### ISSUE TITLE
Blackthorne (1994)

### ISSUE THREAD

**Issue by flynnsbit** [flynnsbit/Top300_updates#4]
Black screen, sounds lock, core locks using EMM or QEMM

**Comment by flynnsbit** [comment]
Demo version works and can replace demo.dat with full data.dat and then run setup, SB Pro and Adlib work for sound.  Any other sound option fails, MIDI doesn't seem to work.
Full version from Blizzard works but doesn't allow sound configuration so you don't get music.  Here is the official released version: https://www.blizzard.com/en-us/download/confirmation?platform=windows&locale=en_US&product=bt

Demo version of setup can modify data.dat from retail.  ExoDOS version and version from original CD get a black screen when starting.

**Comment by FreddoUK** [comment]
https://github.com/flynnsbit/Top300_updates/commit/aa9144ab8cee217493c4fe65a79e2192feacd79b

fixed.
