### ISSUE TITLE
Prisoner of Ice (mount is in run.bat)

### ISSUE THREAD

**Issue by flynnsbit** [flynnsbit/Top300_updates#42]
the mount commands for this game are in the run.bat which prevented the original conversion from working and pulling over the CD.  Needs corrected in the ExoDOSConverter.  change to just cd into cd-us and run the game.  no need to mount.

**Comment by FreddoUK** [comment]
https://github.com/flynnsbit/Top300_updates/commit/517dc8a8063c163808c28360cf5e14721a61bb69

Fixed.
