### ISSUE TITLE
Invalid zip file with overlapped components (possible zip bomb)

### ISSUE THREAD

**Issue by ruthloose88** [flynnsbit/Top300_updates#82]
I tried to run the AO486 updater script this morning on my MiSTer and ran into this issue for the first time. Has there been a major directory change to the project that may be the culprit? I didn't see any other issues for this yet.

**Comment by flynnsbit** [comment]
No, no changes on my side.

**Comment by darkorangewatermelon** [comment]
I'm getting the same error as well

**Comment by flynnsbit** [comment]
you both need to run the main mister updater again.  There were linux changes and zip changes,bugs, then fixes.  Try again and report back so I can close this.

**Comment by darkorangewatermelon** [comment]
You're right, flynnsbit. The main updater fixed the issue. Thank you!
